djmt/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.views.generic.base import TemplateView
from accounts.views import login, register, logout, index
from django.contrib.auth.decorators import login_required
from accounts import urls
from frontend import urls as fron_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^', include(urls), name="accounts"),
    path('', include(fron_urls), name="frontend"),
    url(r'^api/usuarios/', include('accounts.api.urls')),
    url(r'^api/partys/', include('partys.api.urls')),

   
]

djmt/forms.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    keep_logged = forms.BooleanField(required=False, label="Keep me logged in")

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>On-Fire! | Inicio</title>
  

 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <link href="{% static 'materialize1.css' %}" rel="stylesheet">



 <style type="text/css">

 	a:focus, a:hover {
    color: #ef681a;
    text-decoration: underline;
	}

    body, html {
      height: 100%;
    }
    .app-loading {
      position: relative;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100%;
    }


    .app-loading .spinner {
      height: 200px;
      width: 200px;
      animation: rotate 2s linear infinite;
      transform-origin: center center;
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      margin: auto;
    }

    .app-loading .spinner .path {
      stroke-dasharray: 1, 200;
      stroke-dashoffset: 0;
      animation: dash 1.5s ease-in-out infinite;
      stroke-linecap: round;
      stroke: #ddd;
    }

    @keyframes rotate {
      100% {
        transform: rotate(360deg);
      }
    }

    @keyframes dash {
      0% {
        stroke-dasharray: 1, 200;
        stroke-dashoffset: 0;
      }
      50% {
        stroke-dasharray: 89, 200;
        stroke-dashoffset: -35px;
      }
      100% {
        stroke-dasharray: 89, 200;
        stroke-dashoffset: -124px;
      }
    }
  </style>

<style type="text/css">
body {
    overflow-y:hidden;
}

.nav-hove a:hover {
    color: #ef681a;
}

nav {

    background-color: #202020;

</style>

<style type="text/css">
	.img-logo {
		height: 0%;
   		width: 5%;
	}

	nav .sidenav-trigger {
    float: left;
    position: relative;
    z-index: 1;
    height: 58px;
    width: 66px;
    margin: 0 12px;
}
</style>


<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">Perfil</a></li>
  <li class="divider"></li>
  <li><a href="/logout">Salir</a></li>
</ul>


 <div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper nav-hove" >
      <a href="#!" class="brand-logo "> <img class="img-logo sidenav-trigger" src="{% static 'banners/onfire.png' %}"> On-Fire!</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
      	 <li><a href="#/fiestas">Inicio</a></li>
        <li><a href="#/productos">Productos</a></li>
        <li><a href="#/contacto">Contaco</a></li>
        {% if user.is_authenticated %}
			<li>
				<a href="#" class="dropdown-trigger"
				data-target="dropdown1" >
			{{ request.user.username }}</a></li>
			{% else %}
			<li><a href="/login" > Ingresar</a></li>
				{% endif %}	

      </ul>
      {% if user.is_authenticated %}
      <a href="#"  class="sidenav-trigger dropdown-trigger right" data-target="dropdown1"  >{{ request.user.username }}</a>
		{% else %}
		<a href="/login" class="sidenav-trigger dropdown-trigger right"> Ingresar</a>
		{% endif %}
    </div>

  </nav>
</div>
  <ul class="sidenav" id="mobile-demo">
   <li><a href="#/fiestas">Inicio</a></li>
    <li><a href="#/productos">Productos</a></li>
    <li><a href="#/contacto">Contacto</a></li>
  </ul>
       

  <anms-root>
    <div class="app-loading">
      <div class="logo"></div>
      <svg class="spinner" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
      </svg>
    </div>



  </anms-root>

  <body>

   <script src="{% static 'material/js/jquery.js' %}"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   <script src="{% static 'ang/inline.bundle.js' %}"></script>
   <script src="{% static 'ang/polyfills.bundle.js' %}"></script>

    <script type="text/javascript" src="{% static 'ang/vendor.bundle.js' %}"></script>
    <script type="text/javascript" src="{% static 'ang/main.bundle.js' %}"></script>
    <script type="text/javascript" src="{% static 'ang/styles.bundle.js' %}"></script>


 {% include 'material/includes/material_js.html' %}


     <script type="text/javascript">


  
    var elems = document.querySelectorAll('.slider');
    var instances = M.Slider.init(elems, options);


	var options = {
    coverTrigger: false,
    constrainWidth: false,
	};

	var elem = document.querySelector('.dropdown-trigger');
	var dropdown = new M.Dropdown(elem, options);

  	$(".dropdown-trigger").dropdown();


 	var elem = document.querySelector('.sidenav');
	var instance = M.Sidenav.init(elem);

  // Or with jQuery

  $(document).ready(function(){
    $('.mobile-demo').sidenav();

  });


  // Or with jQuery
   
 $(document).ready(function(){
    $('.datepicker').datepicker();
  });
  </script>



	  </body>
  </html>
  

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>On-Fire! | Bienvenido!</title>

   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'materialize.css' %}" rel="stylesheet">






   <style type="text/css">



      html, body {
          background: #eee;
          height: 100%;
      }

      input, select, textarea{
    color: #fafafa;
      }


      .card-color {
            background-color:: #202020
      }
    </style>

    <style type="text/css">

  .img-logo {
    height: 0%;
      width: 15%;
  }

  nav .sidenav-trigger {
    float: left;
    position: relative;
    z-index: 1;
    height: 58px;
    width: 66px;
    margin: 0 12px;
}
</style>
    
<style type="text/css">
    .aligned-with-icon{
  position: absolute;
  margin-top: 5px;
  margin-left: 5px; /* optional */
}
</style>

    
  </head>


  <br>
    <br>
  <body class="valign-wrapper2">
      
      <div class="container expand-on-small-only">
          
<div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
        <div class="card" >
            <form method="POST" enctype='multipart/form-data'>
                 
                <div class="card-content">
                 
                    <a href="/" class="brand-logo "> 

                    <img class="img-logo sidenav-trigger" src="{% static 'banners/onfire.png' %}">
                    <span class=" aligned-with-icon grey-text text-darken-2"><h5> </h5></span>
                  
                    </a>
                    
                    <br>
                  
                    <center>
                    <h5 class="grey-text text-darken-2">¡Hola! Ingresa tu e-mail y contraseña</h6>
                    </center>
                
              {% if form.non_field_errors %}
                <div id="error_login" class="notif col s9 l5"  >  
       

                  <center>{{ form.non_field_errors  }}</center> 
           
            </div>  
             {% endif %}
    
<div class="row">
    <div class="input-field col s12 required" id="email">
        <i class="material-icons prefix">email</i> <input id="email" name="email" type="email" required="" email>
        <label for="email">Correo Electronico</label>
         
        
        
    </div>
</div>



 

<div class="row">
    <div class="input-field col s12 required" id="id_password_container">
        <i class="material-icons prefix">lock</i><input id="password" name="password" type="password" required="" >
        <label for="password">Contraseña</label>
      
        
    </div>
</div>
 
<div class="row">
    <div class="checkbox-field col s12 right-align" id="id_keep_logged_container">
        <label>
        <input class="filled-in " id="id_keep_logged" name="keep_logged" type="checkbox"><span for="id_keep_logged">Recordar cuenta</span></label>
        
    </div>
</div>

   

                </div>
                <div class="card-action">
                    
                    <div class="right-align">
                        
    	
   <label> no tienes una cuenta?</label><a href="/registro" button class="waves-effect waves-teal btn-flat">Registrarse
    	</a>
        
        <button class="btn waves-effect waves-light" type="submit" name="action">Ingresar
  
  </button>
        
     
        {% csrf_token %}
    

                    </div>
                    
                </div>

            </form>
        </div>
    </div>
</div>


<style type="text/css">
  .notif {
  position: fixed;
  top: 5px; 
  left: 50%;
  width: 25%;
  background-color: #323232;
  padding: 12px 24px 17px 24px;
  vertical-align: middle;
  color: #fff;
  box-shadow: 0 7px 18px rgba(0,0,0,0.2);
  border-radius: 1px;
  font-family: "Trebuchet MS", Helvetica, sans-serif;
}

.peek {
    -webkit-animation: peek 5s forwards;
    -webkit-animation-delay: 0.5s;
    animation: peek 5s forwards;
    
}




</style>


      </div>
      


 <script src="{% static 'material/js/jquery.js' %}"></script>
 {% include 'material/includes/material_js.html' %}

<script type="text/javascript">
setTimeout(function() {
    $('#error_login').fadeOut('slow');
}, 3000); // <-- time in milliseconds
</script>


</div>
</div>
</div>
</div>
</body>


</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>On-Fire! | Registrarse</title>
  
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'materialize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'materialize.min.css' %}">
 
 <link href="{% static 'materialize.css' %}" rel="stylesheet">

   <style type="text/css">
      html, body {
          background: #eee;
          height: 100%;
      }
    </style>
    
    <style type="text/css">

  .img-logo {
    height: 0%;
      width: 15%;
  }

  nav .sidenav-trigger {
    float: left;
    position: relative;
    z-index: 1;
    height: 58px;
    width: 66px;
    margin: 0 12px;
}

      input, select, textarea{
    color: #fafafa;
      }

</style>
    
<style type="text/css">
    .aligned-with-icon{
  position: absolute;
  margin-top: 5px;
  margin-left: 5px; /* optional */
}
</style>


    
  </head>
  <br>
    <br>
  <body class="valign-wrapper2">
      
      <div class="container expand-on-small-only">
          
<div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
        <div class="card">
            <form method="POST" enctype='multipart/form-data'>
                 
                <div class="card-content">


                    <a href="/" class="brand-logo "> 

                    <img class="img-logo sidenav-trigger" src="{% static 'banners/onfire.png' %}">
                    <span class=" aligned-with-icon grey-text text-darken-2"><h5> </h5></span>
                  
                    </a>
             <center>
                    <span class="card-title grey-text text-darken-2">Completa tus datos</span>
</center>

    {% if form.errors.username %}
    <div id="error_username2" class="notif col s9 l5">
      {{ form.errors.username }}

      </div>
    {% endif %}



          {% if messages %}
      <div id="error_email" class="notif col s9 l5" >

       
                {% for message in messages %}
            <ul class="errorlist nonfield"><li> <center> Ya existe un usuario con ese nombre. </center></li></ul>
                {% endfor %}
           
        </div>

         {% endif %}
                   
              {% if form.non_field_errors %}
                
                <div id="error_username" class="notif col s9 l5">  
       

                   <center>{{ form.non_field_errors  }}</center>
            </div>  
             {% endif %}


<div class="row">
    <div class="input-field col s12 required" id="username">
        <i class="material-icons prefix">person</i><input  id="username" name="username" type="text" required="">

       
        <label for="username" >Nombre Usuario</label>

        
        
</div>

</div>


<div class="row">
    <div class="input-field col s12 required" id="email">
        <i class="material-icons prefix">email</i> <input  id="email" name="email" type="email" required="" email>
        <label for="email">Correo Electronico</label>



 
</div>
     </div>

<div class="row">
    <div class="input-field col s12 required" id="password">
        <i class="material-icons prefix">lock</i><input  name="password" type="password" required="">
        <label for="password">Contraseña</label>
    <div id="error_pass" style="visibility:show">

       

      </div>
        
    </div>
</div>

 
<div class="row">

</div>

   

                </div>
                <div class="card-action">
                    
                    <div class="right-align">
                        
    
       <label> ya tienes una cuenta?</label> <a href="/login" button class="waves-effect waves-teal btn-flat">Ingresar
      </a>

        

                <button class="waves-effect waves-light btn" type="submit">Registrarse</button>

        {% csrf_token %}
    

                    </div>
                    
                </div>

            </form>
        </div>
    </div>
</div>

<style type="text/css">
  .notif {
  position: fixed;
  top: 5px; 
  left: 50%;
  width: 25%;
  background-color: #323232;
  padding: 12px 24px 17px 24px;
  vertical-align: middle;
  color: #fff;
  box-shadow: 0 7px 18px rgba(0,0,0,0.2);
  border-radius: 1px;
  font-family: "Trebuchet MS", Helvetica, sans-serif;
}

.peek {
    -webkit-animation: peek 5s forwards;
    -webkit-animation-delay: 0.5s;
    animation: peek 5s forwards;
    
}




</style>


      </div>
      


 <script src="{% static 'material/js/jquery.js' %}"></script>
 <script src="{% static 'materialize.js' %}"></script>
  <script src="{% static 'materialize.min.js' %}"></script>
 {% include 'material/includes/material_js.html' %}



<script type="text/javascript">
setTimeout(function() {
    $('#error_username').fadeOut('slow');
}, 3000); //
</script>

<script type="text/javascript">
setTimeout(function() {
    $('#error_username2').fadeOut('slow');
}, 3000); //
</script>

<script type="text/javascript">
setTimeout(function() {
    $('#error_email').fadeOut('slow');
}, 3000); // <-- time in milliseconds
</script>


</body>


</html>